import { GetStaticProps, InferGetStaticPropsType } from "next";
import { getPathsFromContext, getResourceFromContext } from "next-drupal";
import Head from "next/head";
import Link from "next/link";
import { ArticleFull, article_schema } from "../components/Article";

export default function ArticlePage({
  article,
  preview,
}: InferGetStaticPropsType<typeof getStaticProps>) {
  if (!article) return null;

  return (
    <div>
      <Head>
        <title>{article.title} - Drupal and Next.js </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ArticleFull {...article} />
      {preview && (
        <div className="preview-exit-button">
          <Link href="/api/exit-preview">
            <a className="button">Exit preview</a>
          </Link>
        </div>
      )}
    </div>
  );
}

export async function getStaticPaths(context) {
  return {
    paths: await getPathsFromContext(["node--article"], context),
    fallback: true,
  };
}

export const getStaticProps: GetStaticProps = async (context) => {
  const node = await getResourceFromContext("node--article", context, {
    params: {
      include: "field_image,uid",
      "filter[langcode]": context.locale,
    },
  });

  if (!node?.status && !context.preview) {
    return {
      notFound: true,
    } as const; // <- Note: this is needed
  }

  const article = article_schema.parse(node);

  return {
    props: {
      preview: context.preview || false,
      article,
    },
    revalidate: 60,
  };
};
