import Head from "next/head";

export default function Home() {
  return (
    <div id="main-container">
      <Head>
        <title>Drupal and Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">Here we will show a list of posts.</main>
    </div>
  );
}
