import Head from "next/head";
import { getResourceCollectionFromContext } from "next-drupal";

import { ArticleTeaser } from "../components/Article";

export default function Home({ articles }) {
  return (
    <div id="main-container">
      <Head>
        <title>Drupal and Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        {articles?.length ? (
          articles.map((article) => (
            <ArticleTeaser key={article.id} article={article} />
          ))
        ) : (
          <p>No articles found.</p>
        )}
      </main>
    </div>
  );
}

export async function getStaticProps(context) {
  const articles = await getResourceCollectionFromContext(
    "node--article",
    context,
    {
      params: {
        include: "uid,field_image",
        sort: "-created",
        "filter[status]": "1",
      },
    }
  );

  return {
    props: {
      articles,
    },
    revalidate: 60,
  };
}
